INSERT INTO users (username, password_hash) VALUES ("jerbjork", "scrypt:32768:8:1$YWbGwdmMYsm80SuG$ec41c18874fd5496f1500663521a2b40e575890fdb8d88695939a267dc5cc3dba5b9bcb11acf7563ca558b1617bb60f33e0285119140b90e6183685cb81cc60c");

INSERT INTO reviews (title, content, user_id, time) VALUES ("All Systems Red", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", "1", "2025-02-02 21:20:36");
INSERT INTO reviews (title, content, user_id, time) VALUES ("The Hobbit", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", "1", "2025-02-02 21:20:37");
INSERT INTO reviews (title, content, user_id, time) VALUES ("Dune", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", "1", "2025-02-02 21:20:38");
INSERT INTO reviews (title, content, user_id, time) VALUES ("The collapse of the third republic", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", "1", "2025-02-02 21:20:39");
INSERT INTO reviews (title, content, user_id, time) VALUES ("At the Mountains of Madness", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", "1", "2025-02-02 21:20:40");
INSERT INTO reviews (title, content, user_id, time) VALUES ("Best Served Cold", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", "1", "2025-02-02 21:20:41");

INSERT INTO tags (title) VALUES ("fiction");
INSERT INTO tags (title) VALUES ("science fiction");
INSERT INTO tags (title) VALUES ("space");
INSERT INTO tags (title) VALUES ("robots");
INSERT INTO tags (title) VALUES ("fantasy");
INSERT INTO tags (title) VALUES ("high fantasy");
INSERT INTO tags (title) VALUES ("adventure");
INSERT INTO tags (title) VALUES ("science fantasy");
INSERT INTO tags (title) VALUES ("nonfiction");
INSERT INTO tags (title) VALUES ("history");

INSERT INTO attach (tag_id, review_id) VALUES ("1", "1");
INSERT INTO attach (tag_id, review_id) VALUES ("2", "1");
INSERT INTO attach (tag_id, review_id) VALUES ("3", "1");
INSERT INTO attach (tag_id, review_id) VALUES ("4", "1");
INSERT INTO attach (tag_id, review_id) VALUES ("1", "2");
INSERT INTO attach (tag_id, review_id) VALUES ("5", "2");
INSERT INTO attach (tag_id, review_id) VALUES ("6", "2");
INSERT INTO attach (tag_id, review_id) VALUES ("7", "2");
INSERT INTO attach (tag_id, review_id) VALUES ("1", "3");
INSERT INTO attach (tag_id, review_id) VALUES ("2", "3");
INSERT INTO attach (tag_id, review_id) VALUES ("8", "3");
INSERT INTO attach (tag_id, review_id) VALUES ("3", "3");
INSERT INTO attach (tag_id, review_id) VALUES ("9", "4");
INSERT INTO attach (tag_id, review_id) VALUES ("10", "4");
INSERT INTO attach (tag_id, review_id) VALUES ("1", "5");
INSERT INTO attach (tag_id, review_id) VALUES ("5", "5");
INSERT INTO attach (tag_id, review_id) VALUES ("1", "6");
INSERT INTO attach (tag_id, review_id) VALUES ("5", "6");

INSERT INTO messages (time, content, user_id, review_id) VALUES ("2025-02-02 21:20:35", "Some sample text to show what a comments looks like", "1", "1");
INSERT INTO messages (time, content, user_id, review_id) VALUES ("2025-02-02 21:20:36", "Some sample text to show what a comments looks like", "1", "1");
INSERT INTO messages (time, content, user_id, review_id) VALUES ("2025-02-02 21:20:37", "Some sample text to show what a comments looks like", "1", "2");
INSERT INTO messages (time, content, user_id, review_id) VALUES ("2025-02-02 21:20:38", "Some sample text to show what a comments looks like", "1", "2");
INSERT INTO messages (time, content, user_id, review_id) VALUES ("2025-02-02 21:20:39", "Some sample text to show what a comments looks like", "1", "2");
INSERT INTO messages (time, content, user_id, review_id) VALUES ("2025-02-02 21:20:40", "Some sample text to show what a comments looks like", "1", "2");
INSERT INTO messages (time, content, user_id, review_id) VALUES ("2025-02-02 21:20:41", "Some sample text to show what a comments looks like", "1", "3");
INSERT INTO messages (time, content, user_id, review_id) VALUES ("2025-02-02 21:20:42", "Some sample text to show what a comments looks like", "1", "3");
INSERT INTO messages (time, content, user_id, review_id) VALUES ("2025-02-02 21:20:43", "Some sample text to show what a comments looks like", "1", "3");
INSERT INTO messages (time, content, user_id, review_id) VALUES ("2025-02-02 21:20:44", "Some sample text to show what a comments looks like", "1", "4");
INSERT INTO messages (time, content, user_id, review_id) VALUES ("2025-02-02 21:20:44", "Some sample text to show what a comments looks like", "1", "4");
INSERT INTO messages (time, content, user_id, review_id) VALUES ("2025-02-02 21:20:45", "Some sample text to show what a comments looks like", "1", "4");
INSERT INTO messages (time, content, user_id, review_id) VALUES ("2025-02-02 21:20:46", "Some sample text to show what a comments looks like", "1", "5");
INSERT INTO messages (time, content, user_id, review_id) VALUES ("2025-02-02 21:20:47", "Some sample text to show what a comments looks like", "1", "5");
INSERT INTO messages (time, content, user_id, review_id) VALUES ("2025-02-02 21:20:47", "Some sample text to show what a comments looks like", "1", "5");
INSERT INTO messages (time, content, user_id, review_id) VALUES ("2025-02-02 21:20:47", "Some sample text to show what a comments looks like", "1", "6");
INSERT INTO messages (time, content, user_id, review_id) VALUES ("2025-02-02 21:20:47", "Some sample text to show what a comments looks like", "1", "6");
INSERT INTO messages (time, content, user_id, review_id) VALUES ("2025-02-02 21:20:47", "Some sample text to show what a comments looks like", "1", "6");
