DELETE FROM categories;

INSERT INTO categories (title) VALUES ("Adult");
INSERT INTO categories (title) VALUES ("Adventure");
INSERT INTO categories (title) VALUES ("Childrens");
INSERT INTO categories (title) VALUES ("Contemporary");
INSERT INTO categories (title) VALUES ("Crime");
INSERT INTO categories (title) VALUES ("Fiction");
INSERT INTO categories (title) VALUES ("History");
INSERT INTO categories (title) VALUES ("Horror");
INSERT INTO categories (title) VALUES ("Mystery");
INSERT INTO categories (title) VALUES ("Non-fiction");
INSERT INTO categories (title) VALUES ("Philosophy");
INSERT INTO categories (title) VALUES ("Poetry");
INSERT INTO categories (title) VALUES ("Politics");
INSERT INTO categories (title) VALUES ("Romance");
INSERT INTO categories (title) VALUES ("Science");
INSERT INTO categories (title) VALUES ("Science Fiction");
INSERT INTO categories (title) VALUES ("Young-adult");
INSERT INTO categories (title) VALUES ("War");